baseURL = 'https://sunyzhi55.github.io/hugo-reimu-blog/'

title = 'æ°£é«”æºæµ'
theme = ["github.com/D-Sketon/hugo-theme-reimu"]
languageCode = 'zh-CN'
defaultContentLanguage = 'zh-CN'

tags = ['Blog', 'Chinese', 'Responsive', 'Dark', 'Light']
features = ['Blog', 'Chinese', 'Responsive', 'Dark', 'Light']

[author]
name = 'ğŸ•¯ Glow'
homepage = 'https://sunyzhi55.github.io/'

[languages]
[languages.zh-CN]
languageName = 'ç®€ä½“ä¸­æ–‡'
weight = 1
hasCJKLanguage = true
[markup.highlight]
guessSyntax = true
noClasses = false

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.extensions.passthrough]
enable = true
delimiters.block = [["\\[", "\\]"], ["$$", "$$"]]
delimiters.inline = [["\\(", "\\)"], ["$", "$"]]